version: '3'
services:
    app:
        build: .
        tty: true
        stdin_open: true
        ports:
            - "3000:3000"
        env_file:
            - .env
        volumes:
            - .:/app:delegated